scrape_configs:
- job_name: sloth_service
  scrape_interval: 10s
  static_configs:
  - targets:
    - host.docker.internal:9000
- job_name: sloth_jump_service
  scrape_interval: 10s
  static_configs:
  - targets:
    - host.docker.internal:9001
